version: "3.9"

services:
  dev:
    build:
      context: .
      target: development
    image: learn-dev
    container_name: learn-dev-container
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"

  prod:
    build:
      context: .
    image: learn-prod
    container_name: learn-prod-container
    ports:
      - "80:80"
