name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      PROJECT_PATH: /path/to/your/project

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy repository to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: "."
          target: ${{ env.PROJECT_PATH }}

      - name: Install dependencies and build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            npm install
            npm run build

      - name: Move build to target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            cp -r ${{ env.PROJECT_PATH }}/dist/* /var/www/html/
